language: perl
perl:
  - "5.30"
  - "5.28"
  - "5.26"
  - "5.22"
before_install:
  - cpanm --quiet --installdeps --notest .
script:
  - perl Makefile.PL
  - make 
  - make install
  - kadoc.pl -v
  - kadoc.pl -h
